name: datFlux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v -o datflux ./cmd/datflux

    - name: Verify binary
      run: |
        if [ ! -f "datflux" ]; then
          echo "Binary was not created"
          exit 1
        fi
        file datflux

    - name: Test
      run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
        golangci-lint --version

    - name: Run golangci-lint
      run: golangci-lint run ./... --timeout=5m
