name: datFlux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v -o datflux ./cmd/datflux

    - name: Verify binary
      run: |
        if [ ! -f "datflux" ]; then
          echo "Binary was not created"
          exit 1
        fi
        file datflux

    - name: Test
      run: go test -v ./...

    - name: Basic Linting
      run: |
        go vet ./...
        if [ $? -ne 0 ]; then
          echo "go vet found issues"
          exit 1
        fi
        
        # Check for formatting issues
        gofmt_output=$(gofmt -l .)
        if [ -n "$gofmt_output" ]; then
          echo "The following files have formatting issues:"
          echo "$gofmt_output"
          exit 1
        fi
        
        echo "Basic linting passed!"
